// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ONGAnimaisAPI.Infra;

#nullable disable

namespace ONGAnimaisAPI.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230921232337_ConfigTabelasRelacionaisONG")]
    partial class ConfigTabelasRelacionaisONG
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ONGAnimaisAPI.Domain.Entities.ONG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("ONGs", (string)null);
                });

            modelBuilder.Entity("ONGAnimaisAPI.Domain.Entities.ONG", b =>
                {
                    b.OwnsMany("ONGAnimaisAPI.Domain.Entities.ValueObjects.Contato", "Contatos", b1 =>
                        {
                            b1.Property<int>("ONGId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasColumnType("VARCHAR(100)");

                            b1.Property<string>("URL")
                                .IsRequired()
                                .HasColumnType("VARCHAR(500)");

                            b1.HasKey("ONGId", "Id");

                            b1.ToTable("OngContato", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ONGId");
                        });

                    b.OwnsOne("ONGAnimaisAPI.Domain.Entities.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("ONGId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("VARCHAR(150)");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasColumnType("VARCHAR(8)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("VARCHAR(150)");

                            b1.Property<string>("Complemento")
                                .HasColumnType("VARCHAR(150)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnType("VARCHAR(150)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("VARCHAR(20)");

                            b1.Property<string>("UF")
                                .IsRequired()
                                .HasColumnType("VARCHAR(2)");

                            b1.HasKey("ONGId");

                            b1.ToTable("OngEndereco", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ONGId");
                        });

                    b.OwnsMany("ONGAnimaisAPI.Domain.Entities.ValueObjects.Telefone", "Telefones", b1 =>
                        {
                            b1.Property<int>("ONGId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DDD")
                                .IsRequired()
                                .HasColumnType("VARCHAR(2)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("VARCHAR(9)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("VARCHAR(10)");

                            b1.HasKey("ONGId", "Id");

                            b1.ToTable("OngTelefone", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ONGId");
                        });

                    b.Navigation("Contatos");

                    b.Navigation("Endereco");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
